# Generated by Django 3.0.8 on 2020-08-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Douyin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('albummid', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('image', models.CharField(max_length=255)),
                ('mid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('singer', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField()),
                ('timer', models.IntegerField()),
                ('update_time', models.DateTimeField()),
                ('kugou_url', models.CharField(max_length=255)),
                ('play_mode', models.CharField(max_length=255)),
                ('other_url', models.CharField(max_length=255)),
                ('local_url', models.CharField(max_length=255)),
                ('disabled', models.CharField(max_length=255)),
                ('lyric', models.CharField(max_length=5000)),
                ('local_image', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '抖音',
                'verbose_name_plural': '抖音',
                'db_table': 'douyin',
            },
        ),
        migrations.CreateModel(
            name='FavoriteMusic',
            fields=[
                ('id', models.IntegerField()),
                ('albummid', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('image', models.CharField(max_length=255)),
                ('mid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('singer', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField()),
                ('timer', models.IntegerField()),
                ('update_time', models.DateTimeField()),
                ('kugou_url', models.CharField(max_length=255)),
                ('play_mode', models.CharField(max_length=255)),
                ('other_url', models.CharField(max_length=255)),
                ('local_url', models.CharField(max_length=255)),
                ('disabled', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('lyric', models.CharField(max_length=5000)),
                ('local_image', models.CharField(max_length=255)),
                ('favorite_music_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': '收藏音乐表',
                'verbose_name_plural': '收藏音乐表',
                'db_table': 'favorite_music',
            },
        ),
        migrations.CreateModel(
            name='RecordMusic',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('albummid', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('image', models.CharField(max_length=255)),
                ('mid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('singer', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField()),
                ('timer', models.IntegerField()),
            ],
            options={
                'verbose_name': '记录音乐表',
                'verbose_name_plural': '记录音乐表',
                'db_table': 'record_music',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
                ('username', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('avater', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('secret_key', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 'user',
            },
        ),
    ]
